version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres_DP"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: dpuser
      POSTGRES_PASSWORD: dppass
      POSTGRES_DB: dpdb
    ports:
      - "5432:5432"
  pgadmin:
    image: "dpage/pgadmin4"
    restart: always
    container_name: "pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    links:
#      - postgres:postgres
    ports:
      - "5050:80"
volumes:
  pgdata: